## Basic Configuration
baseurl = "https://example.com/"
languageCode = "en"

theme = "hyde-hyde"

## Hugo Built-in Features
# disqusShortname = "your-disqus-shortname"
# googleAnalytics = "your-google-analytics-id"
# enableRobotsTXT = true

## Site Settings
[params]
    author = "Tony D"
    title = "Title"
    description = "Tony Duan"
    authorimage = "/img/home_pic.jpg"
    dateformat = "Jan 2, 2006"
    highlightjs = true
    highlightjsstyle = "github"
    # please choose either GraphComment or Disqus

## Social Accounts
[params.social]
    github = "<username>"
    linkedin = "<username>"
    twitter = "<username>"
    facebook = "<username>"
    stackoverflow = "<username>"
    telegram = "<username>"
    email = "your-email@example.com"

## Main Menu

[[menu.main]]
    name = "Home"
    weight = 1
    identifier = "home"
    url = "http://127.0.0.1:4321/"
    
        
    [[menu.main]]
    name = "Blog"
    weight = 2
    identifier = "blog"
    url = "/blog/"
    
[[menu.main]]
    name = "Project"
    identifier = "portfolio"
    weight = 3
    url = "/portfolio/"
    
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 4
    url = "/about/"
